// database.js
const DATABASE = {
            bibbia: [
                ["Codice Antico", "I rotoli del Mar Morto confermano i testi sacri"],
                ["Primo Uomo", "Adamo doveva coltivare e aver cura del giardino"],
                ["Re Sapiente", "Salomone chiese un cuore ubbidiente a Dio"],
                ["Uomo Integro", "Giobbe non perse fede nonostante le sofferenze"],
                ["Arca Gigante", "Noè costruì un vascello per salvare la vita"],
                ["Leggi di Pietra", "Mosè ricevette dieci leggi sul monte Sinai"],
                ["Buon Pastore", "Il salmo ventitré descrive la cura divina"],
                ["Profeta in Mare", "Giona restò tre giorni nel ventre di un pesce"],
                ["Mura di Corno", "Il suono delle trombe abbatté le mura di Gerico"],
                ["Lotta Sacra", "Giacobbe lottò con un angelo per il favore"],
                ["Sogni Egizi", "Giuseppe spiegò i sogni delle vacche magre"],
                ["Luce ad Est", "Astrologi seguirono una stella fino a Gesù"],
                ["Vento Sacro", "Lo spirito scese come lingue di fuoco"],
                ["Buon Prossimo", "La parabola del samaritano insegna l'amore"],
                ["Sasso e Fionda", "Davide sconfisse il gigante con una pietra"],
                ["Olio Infinito", "Una vedova pagò i debiti con l'olio miracoloso"],
                ["Cesto sul Nilo", "Mosè neonato fu salvato dalle acque del fiume"],
                ["Torre Alta", "La confusione delle lingue fermò Babele"],
                ["Fuoco dal Cielo", "Elia invocò una fiamma sul monte Carmelo"],
                ["Tuniche", "Dio vestì i primi umani con pelli di animali"],
                ["Perla Rara", "Un mercante vendette tutto per un tesoro"],
                ["Visione", "Giovanni scrisse l'apocalisse nell'isola di Patmos"],
                ["Figlio Perso", "Il padre riabbracciò il figlio prodigo"],
                ["Vino a Cana", "Il primo miracolo avvenne durante le nozze"],
                ["Apostoli", "I discepoli parlarono lingue straniere"],
                ["Regina Saba", "Una sovrana testò Salomone con enigmi"],
                ["Manna", "Gli israeliti mangiarono pane caduto dal cielo"],
                ["Arpa", "Davide suonava per calmare lo spirito di Saul"],
                ["Primo Odio", "Caino uccise il fratello Abele per gelosia"],
                ["Genitori", "Abraamo ebbe un figlio in età molto avanzata"],
                ["Mar Rosso", "Le acque si divisero per far passare il popolo"],
                ["Forza", "Sansone usò una mascella d'asino in battaglia"],
                ["Capelli", "Assalonne restò appeso ai rami di un rovere"],
                ["Profezia", "Daniele indicò l'anno dell'arrivo del Messia"],
                ["Esempi", "Uomini di fede sono una nuvola di testimoni"],
                ["Sacco", "Giuseppe nascose una coppa per prova"],
                ["Fiamme", "Tre ebrei restarono illesi nel forno ardente"],
                ["Amore", "Paolo scrisse che la carità non fallisce mai"],
                ["Scala", "Giacobbe sognò angeli che salivano al cielo"],
                ["Preghiera", "Gesù pregava spesso sul monte degli Ulivi"],
                ["Reti", "I primi discepoli erano umili pescatori"],
                ["Gallo", "Pietro rinnegò il maestro prima dell'alba"],
                ["Carestia", "Sette anni di carestia colpirono l'Egitto"],
                ["Piaghe", "Dieci flagelli piegarono l'orgoglio del re"],
                ["Promessa", "Dio asciugherà ogni lacrima dai nostri occhi"],
                ["Giardino", "L'albero della vita era nel mezzo di Eden"],
                ["Luce", "Saulo vide un lampo sulla via di Damasco"],
                ["Pozzo", "La samaritana chiese l'acqua della vita"],
                ["Sermone", "Gesù insegnò le beatitudini sulla montagna"],
                ["Fine", "Mosè vide la terra promessa dal monte Nebo"]
            ],
            creazione: [
                ["Vento", "Le correnti d'aria modellano le dune sabbiose"],
                ["Respiro", "Le foreste pluviali generano ossigeno vitale"],
                ["Giorno", "La rotazione terrestre crea l'alba e il tramonto"],
                ["Pioggia", "Il ciclo dell'acqua nutre ogni forma di vita"],
                ["Neve", "Ogni cristallo di ghiaccio è un pezzo unico"],
                ["Tramonto", "La luce solare colora il cielo di arancione"],
                ["Bussola", "Gli uccelli usano il magnetismo per viaggiare"],
                ["Ghianda", "Un piccolo seme contiene una quercia intera"],
                ["Foglia", "La fotosintesi trasforma la luce in energia"],
                ["Abissi", "Creature strane vivono nel buio degli oceani"],
                ["Corallo", "Le barriere sono città per pesci colorati"],
                ["Scudo", "L'atmosfera ci protegge dai raggi solari"],
                ["Alveare", "Le api costruiscono celle esagonali perfette"],
                ["Bruco", "La metamorfosi crea una farfalla dal bozzolo"],
                ["Funghi", "Le radici degli alberi parlano tramite funghi"],
                ["Balena", "Il gigante azzurro è il re dei mammiferi"],
                ["Polo", "Gli orsi bianchi vivono sui ghiacci artici"],
                ["Magma", "Il fuoco sotterraneo crea nuove terre emerse"],
                ["Maree", "La luna attira le grandi masse d'acqua"],
                ["Oceano", "La vita è nata nelle acque dei mari caldi"],
                ["Stelle", "Le nebulose sono culle di nuovi soli"],
                ["Mimetismo", "Il camaleonte scompare tra le foglie verdi"],
                ["Diga", "Il castoro modifica il corso dei fiumi"],
                ["Cellula", "Un intero mondo vive in una goccia di vita"],
                ["Oasi", "L'acqua nel deserto crea isole di verde"],
                ["Arcobaleno", "La pioggia scompone la luce in sette colori"],
                ["Colibrì", "L'uccello mosca vola restando fermo nell'aria"],
                ["Dna", "La spirale della vita contiene ogni segreto"],
                ["Lupi", "L'ululato serve a radunare tutto il branco"],
                ["Squali", "Questi pesci sentono i battiti delle prede"],
                ["Asse", "L'inclinazione del pianeta crea le stagioni"],
                ["Fiori", "La vita sboccia anche tra le pietre dure"],
                ["Galassia", "Miliardi di stelle formano la Via Lattea"],
                ["Guscio", "La tartaruga porta la casa sempre con sé"],
                ["Plancton", "Piccole alghe producono metà dell'ossigeno"],
                ["Vette", "Sulle cime dei monti crescono solo licheni"],
                ["Catena", "Ogni animale ha un ruolo nel ciclo vitale"],
                ["Rugiada", "Al mattino l'erba si copre di perle d'acqua"],
                ["Gufo", "Le piume soffici rendono il volo silenzioso"],
                ["Stalattite", "La pietra cresce di un millimetro al secolo"],
                ["Sabbia", "L'erosione riduce le montagne in granelli"],
                ["Stormo", "Gli uccelli volano a V per faticare meno"],
                ["Girasole", "Il fiore si gira seguendo il disco solare"],
                ["Nucleo", "Il cuore di ferro fuso crea il campo magnetico"],
                ["Terme", "Il calore della terra scalda l'acqua pura"],
                ["Libellula", "Le ali doppie sono capolavori di ingegneria"],
                ["Profumi", "I fiori attirano gli insetti con gli odori"],
                ["Ghepardo", "Il felino scatta a cento orari in un attimo"],
                ["Ghiaccio", "L'Antartide è una distesa bianca e gelida"],
                ["Soffione", "I semi volano lontano come paracadute"]
            ],
            curiosita: [
                ["Koala", "Questi animali hanno impronte come le umane"],
                ["Miele", "Questo cibo non scade mai e resta buono"],
                ["Cuore", "Il cuore della balena è grande come un'auto"],
                ["Grillo", "Le orecchie dei grilli sono sulle zampe"],
                ["Delfino", "Questi cetacei dormono con un occhio aperto"],
                ["Giraffa", "La loro lingua è blu e lunga mezzo metro"],
                ["Diamanti", "Su Nettuno piove carbonio cristallizzato"],
                ["Rosa", "I fenicotteri sono rosa per via dei gamberi"],
                ["Volo", "Il colibrì vola anche all'indietro velocemente"],
                ["Polpo", "Questo animale ha tre cuori e sangue blu"],
                ["Stelle", "Lo scarabeo si orienta con la Via Lattea"],
                ["Gusto", "Le farfalle sentono i sapori con le zampe"],
                ["Fungo", "Esiste un fungo grande come molti campi"],
                ["Tigre", "Le strisce sono disegnate anche sulla pelle"],
                ["Sassi", "I coccodrilli mangiano pietre per immergersi"],
                ["Rana", "Il veleno di una rana uccide dieci uomini"],
                ["Maiali", "Si rotolano nel fango per rinfrescarsi"],
                ["Canto", "La balena azzurra si sente a otto cento km"],
                ["Occhio", "Lo struzzo ha gli occhi più grandi del cervello"],
                ["Gatti", "I gatti miagolano solo per parlare con noi"],
                ["Bradipo", "Digerire una foglia richiede due settimane"],
                ["Lumaca", "Una chiocciola ha migliaia di denti minuscoli"],
                ["Formiche", "Pesano quanto tutta la popolazione umana"],
                ["Naso", "Il naso del cane è unico come una impronta"],
                ["Castoro", "La coda piatta serve da timone nell'acqua"],
                ["Orecchie", "Il gatto ruota le orecchie di gradi cento ottanta"],
                ["Sangue", "Il pipistrello ha un morso che non fa male"],
                ["Mucca", "I bovini hanno uno stomaco con quattro camere"],
                ["Narvalo", "Il suo corno è in realtà un dente lunghissimo"],
                ["Pelle", "Il serpente cambia pelle per poter crescere"],
                ["Api", "Per un chilo di miele servono milioni di fiori"],
                ["Cervello", "La mente umana accende una piccola lampadina"],
                ["Pesci", "I pesci rossi ricordano le cose per mesi"],
                ["Pupille", "Le capre hanno gli occhi di forma rettangolare"],
                ["Gufo", "Vola nel buio senza fare il minimo rumore"],
                ["Cammello", "Può chiudere il naso durante le tempeste"],
                ["Seppia", "Usa una nuvola nera per scappare dai nemici"],
                ["Noci", "Gli scoiattoli piantano alberi senza volerlo"],
                ["Gelo", "L'acqua calda congela prima della fredda"],
                ["Nidi", "I gorilla dormono in letti fatti di foglie"],
                ["Orso", "Sotto il pelo bianco la pelle dell'orso è nera"],
                ["Pulce", "Salta una distanza pari a duecento volte lei"],
                ["Squalo", "Questi pesci non hanno ossa ma cartilagine"],
                ["Sonno", "Il koala dorme ventidue ore ogni giorno"],
                ["Coda", "La lucertola la stacca per fuggire via"],
                ["Viaggi", "Alcuni rondoni volano per mesi senza sosta"],
                ["Grilli", "Suonano sfregando le ali tra di loro"],
                ["Elefante", "Le grandi orecchie servono come radiatori"],
                ["Armadillo", "Questo mammifero ha una corazza di osso"],
                ["Bacio", "Le giraffe non emettono suoni udibili"]
            ],
            geografia: [
                ["Everest", "La vetta cresce di pochi millimetri ogni anno"],
                ["Islanda", "Qui le placche della terra si separano"],
                ["Nilo", "Il fiume attraversa undici nazioni diverse"],
                ["Mangrovie", "Queste piante proteggono le coste dal mare"],
                ["Abisso", "La fossa delle Marianne è profonda undici km"],
                ["Sahara", "Un tempo il deserto era una distesa verde"],
                ["Barriera", "Il corallo australiano si vede dallo spazio"],
                ["Antartide", "Contiene gran parte dell'acqua dolce al mondo"],
                ["Cascata", "Il Salto Angel scende per mille metri"],
                ["Istanbul", "La città sorge su due continenti diversi"],
                ["Specchio", "Il deserto di sale diventa un vetro enorme"],
                ["Congo", "Ospita la seconda foresta più grande al mondo"],
                ["Fiordi", "I ghiacciai hanno scavato le coste norvegesi"],
                ["Vulcani", "L'anello di fuoco circonda il Pacifico"],
                ["Mar Caspio", "In realtà è il lago più esteso del pianeta"],
                ["Alpi", "Il Monte Bianco è il tetto della nostra Europa"],
                ["Venezia", "La città poggia su milioni di pali di legno"],
                ["Cina", "La grande muraglia non è una linea continua"],
                ["Siberia", "Il permafrost è il suolo gelato dei russi"],
                ["Mekong", "Il delta ospita migliaia di risaie fertili"],
                ["Uluru", "Il grande sasso rosso è sacro agli indigeni"],
                ["Gibilterra", "Lo stretto separa l'Europa dall'Africa"],
                ["Iguazú", "Sono quasi trecento cascate tra due stati"],
                ["Inca", "Machu Picchu si trova in alto sulle Ande"],
                ["Sinai", "Il deserto collega l'Africa con l'Asia"],
                ["Canada", "Ha più laghi di tutto il resto del mondo"],
                ["Giappone", "Il monte Fuji è un vulcano dalla forma pura"],
                ["Isole", "L'Indonesia ha oltre diciassettemila isole"],
                ["Maldive", "Gli atolli rischiano di finire sott'acqua"],
                ["Prateria", "Le grandi pianure sono lunghe migliaia di km"],
                ["Canyon", "Il fiume ha scavato la roccia per ere"],
                ["Germania", "La foresta nera è piena di abeti fittissimi"],
                ["Finlandia", "Qui ci sono quasi duecentomila laghi"],
                ["Capo", "Il punto estremo non è quello più a sud"],
                ["Somalia", "Ha la costa più lunga di tutta l'Africa"],
                ["Australia", "Un continente con animali unici al mondo"],
                ["Geyser", "In Nuova Zelanda l'acqua bolle nel suolo"],
                ["Gobi", "Il deserto asiatico è freddo e ventoso"],
                ["Vetta", "Il Kilimangiaro ha la cima sempre innevata"],
                ["Artico", "Un oceano di ghiaccio senza terra sotto"],
                ["Oasi", "L'acqua sotterranea fa vivere il deserto"],
                ["Maestrale", "Il vento freddo che soffia sul Mediterraneo"],
                ["Tibet", "L'altopiano è il tetto del mondo intero"],
                ["Irlanda", "L'isola è verde per via delle piogge"],
                ["Limo", "Il fiume giallo trasporta fango fertile"],
                ["Vaticano", "Lo stato più piccolo è nel cuore di Roma"],
                ["Mar Morto", "Si trova nel punto più basso della terra"],
                ["Ande", "La catena montuosa più lunga del pianeta"],
                ["Egitto", "Senza il Nilo non ci sarebbe agricoltura"],
                ["Sydney", "La baia è una delle più belle del mondo"]
            ],
            musica: [
                ["Beethoven", "Il genio scrisse musica pur essendo sordo"],
                ["Vivaldi", "Le stagioni descrivono il tempo con i suoni"],
                ["Violoncello", "Il suo suono sembra una voce umana calda"],
                ["Note", "I segni sul foglio dicono come suonare"],
                ["Direttore", "Guida l'orchestra senza fare rumore"],
                ["Piano", "Può suonare sia piano che molto forte"],
                ["Opera", "Canto e teatro si uniscono sul palco"],
                ["Ritmo", "Le percussioni sono il cuore della musica"],
                ["Jazz", "Gli artisti inventano le note sul momento"],
                ["Tromba", "I tre pistoni cambiano le note nel tubo"],
                ["Schubert", "La sua sinfonia restò a metà per sempre"],
                ["Canzoni", "Alcuni testi sono poesie molto profonde"],
                ["Coro", "Molte persone cantano insieme in armonia"],
                ["Chitarra", "Il rock usa corde di metallo ed elettricità"],
                ["Folk", "Le storie del popolo volano tra le note"],
                ["Sintetizzatore", "Crea ogni suono con i circuiti elettrici"],
                ["Monastero", "Il canto gregoriano si canta senza musica"],
                ["Vinile", "Il disco nero che gira sta tornando di moda"],
                ["Tempo", "Il metronomo batte il ritmo con precisione"],
                ["Sanremo", "Il festival celebra la canzone italiana"],
                ["Blues", "Le note blu danno un senso di malinconia"],
                ["Teatro", "L'acustica fa sentire tutto fino in fondo"],
                ["Film", "Le immagini sono più forti con la musica"],
                ["Arpa", "Le corde d'oro suonano musiche magiche"],
                ["Organo", "Lo strumento gigante ha canne di metallo"],
                ["Accordo", "Suoni diversi che stanno bene insieme"],
                ["Tensione", "La dissonanza chiede di essere risolta"],
                ["Dita", "Il pizzicato si fa senza usare l'archetto"],
                ["Rossini", "Il crescendo aumenta il volume pian piano"],
                ["Stradivari", "I suoi violini valgono milioni di euro"],
                ["Metallo", "Il vibrafono ha tasti che tremano"],
                ["Tango", "La fisarmonica suona ritmi del Sudamerica"],
                ["Oboe", "Il fiato di legno ha un suono nasale"],
                ["Basso", "Il contrabbasso fa vibrare il pavimento"],
                ["Flauto", "L'aria soffia nel foro senza usare ance"],
                ["Voci", "Il canto a cappella non usa strumenti"],
                ["Inno", "La gioia di Beethoven è il simbolo europeo"],
                ["Gershwin", "Unì la musica classica con il ritmo jazz"],
                ["Bocca", "Il beatbox imita la batteria con la gola"],
                ["Tastiera", "Un computer che suona come una orchestra"],
                ["Pentagramma", "Le cinque righe dove nascono le melodie"],
                ["Chiave", "Il segno di basso serve per le note gravi"],
                ["Danza", "Il minuetto si ballava nelle corti antiche"],
                ["India", "Il sitar ha corde che vibrano da sole"],
                ["Sax", "Il tubo d'ottone è nato per le bande"],
                ["Triangolo", "Il pezzetto di ferro fa un suono acuto"],
                ["Barocco", "Il clavicembalo faceva la base armonica"],
                ["Dodici", "La scala cromatica usa tutti i tasti"],
                ["Falsetto", "Gli uomini cantano note molto alte"],
                ["Messa", "Il requiem è una musica per i defunti"]
            ],
            proverbi: [
                ["Pesci", "Chi dorme non piglia pesci nel suo secchio"],
                ["Erba", "L'erba del vicino sembra sempre la migliore"],
                ["Sacco", "Non dire quattro se non l'hai nel sacco"],
                ["Tesoro", "Chi trova un amico trova un grande bene"],
                ["Bugie", "Le bugie hanno sempre le gambe molto corte"],
                ["Cielo", "Rosso di sera bel tempo si spera domani"],
                ["Caval", "A caval donato non si guarda nella bocca"],
                ["Gatta", "La gatta frettolosa fece i figli ciechi"],
                ["Cuore", "Lontano dagli occhi lontano dal cuore"],
                ["Monaco", "L'abito non fa mai il monaco nel convento"],
                ["Lupo", "Il lupo perde il pelo ma non il suo vizio"],
                ["Pesce", "L'ospite dopo tre giorni puzza come pesce"],
                ["Brodo", "Gallina vecchia fa sempre un buon brodo"],
                ["Cane", "Can che abbaia non morde chi gli passa"],
                ["Braccio", "A dare unito si prendono tutto il braccio"],
                ["Vento", "Chi semina vento raccoglie la tempesta"],
                ["Piatto", "Non sputare nel piatto in cui mangi"],
                ["Moglie", "Moglie e buoi dei paesi tuoi è meglio"],
                ["Uovo", "Meglio un uovo oggi che una gallina domani"],
                ["Botte", "Nella botte piccola c'è il vino buono"],
                ["Forti", "La pazienza è la virtù di chi è forte"],
                ["Oro", "Il silenzio è d'oro ma la parola è d'argento"],
                ["Roma", "Tutte le strade portano alla città eterna"],
                ["Panni", "I panni sporchi si lavano solo in casa"],
                ["Chiodo", "Un chiodo scaccia l'altro chiodo vecchio"],
                ["Monte", "Se il monte non va da lui lui va al monte"],
                ["Fumo", "Tutto fumo e niente arrosto nel caminetto"],
                ["Erba", "Campa cavallo che l'erba cresce piano"],
                ["Diavolo", "Il diavolo fa le pentole ma non i coperchi"],
                ["Muri", "Anche i muri hanno le orecchie per sentire"],
                ["Barca", "Siamo tutti sulla stessa barca in mare"],
                ["Osso", "Due cani per un osso non fanno mai pace"],
                ["Miele", "Si prendono più mosche con il miele dolce"],
                ["Libro", "Non giudicare il libro dalla copertina"],
                ["Ferro", "Batti il ferro finché è ancora caldo"],
                ["Rose", "Non c'è rosa senza le sue spine pungenti"],
                ["Grano", "Bisogna saper dividere il grano dal loglio"],
                ["Appetito", "L'appetito viene mangiando a tavola"],
                ["Zoppo", "Chi va con lo zoppo impara a zoppicare"],
                ["Conti", "I conti chiari fanno l'amicizia lunga"],
                ["Vita", "Finché c'è vita c'è speranza per tutti"],
                ["Dente", "La lingua batte dove il dente duole"],
                ["Sole", "Il sole bacia i belli e scalda i brutti"],
                ["Impara", "Non si smette mai di imparare nella vita"],
                ["Letto", "Chi ben comincia è a metà della sua opera"],
                ["Tavola", "Aggiungi un posto a tavola per l'amico"],
                ["Vicino", "Rispetta il prato di chi vive accanto"],
                ["Sacco", "Sacco vuoto non sta in piedi da solo"],
                ["Tempo", "Il tempo è galantuomo con ogni persona"],
                ["Paese", "Tutto il mondo è paese per chi viaggia"]
            ],
            scienza: [
                ["Materia", "Tutto ciò che vediamo è quasi tutto vuoto"],
                ["Luce", "Il raggio solare arriva in otto minuti"],
                ["Corpo", "Sostituiamo milioni di cellule ogni istante"],
                ["Genoma", "Il codice della vita è scritto nel nucleo"],
                ["Acqua", "La pressione aumenta ogni dieci metri"],
                ["Stelle", "I soli nascono da nubi di gas e polvere"],
                ["Orbita", "Gli astronauti cadono per restare in volo"],
                ["Neuroni", "La mente parla con scariche elettriche"],
                ["Calamita", "Il ferro nel cuore della terra ci guida"],
                ["Nucleare", "Il sole fonde atomi per darci energia"],
                ["Suono", "Le onde sonore non viaggiano nel vuoto"],
                ["Batteri", "Nel corpo abbiamo più microbi che cellule"],
                ["Specie", "Chi si adatta meglio riesce a vivere"],
                ["Licheni", "Sono una unione tra un fungo e una alga"],
                ["Gravità", "La massa dei mondi curva lo spazio-tempo"],
                ["Atomi", "Sono fatti di protoni e piccoli elettroni"],
                ["Gas", "L'effetto serra tiene calda la terra"],
                ["Piante", "Le foglie mangiano la luce per crescere"],
                ["Tempo", "Il tempo rallenta se vai molto veloce"],
                ["Carbonio", "Ogni molecola della vita usa questo atomo"],
                ["Calore", "L'energia passa sempre dal caldo al freddo"],
                ["Buio", "Nulla può sfuggire da un buco nero denso"],
                ["Mistero", "La materia oscura è ovunque ma invisibile"],
                ["Confine", "L'orizzonte degli eventi è senza ritorno"],
                ["Spirale", "La forma del DNA protegge i nostri geni"],
                ["Mare", "Gli oceani mangiano anidride carbonica"],
                ["Proteine", "Piccole macchine costruiscono i tessuti"],
                ["Sangue", "I globuli bianchi mangiano i virus cattivi"],
                ["Energia", "Nulla si distrugge ma tutto si trasforma"],
                ["Esplosione", "La supernova crea i metalli pesanti"],
                ["Tavola", "Mendeleev ordinò gli elementi chimici"],
                ["Nano", "Le cose molto piccole seguono altre leggi"],
                ["Medicina", "I vaccini insegnano al corpo a difendersi"],
                ["Antibiotici", "Questi farmaci uccidono solo i batteri"],
                ["Ciclo", "Gli atomi girano tra aria terra e vita"],
                ["Specchio", "Vediamo gli altri e ci attiviamo anche noi"],
                ["Campo", "La terra ha uno scudo contro il vento di fuoco"],
                ["Disordine", "L'entropia dell'universo aumenta sempre"],
                ["Onde", "La radio usa segnali che non vediamo"],
                ["Occhi", "Vediamo solo una piccola parte della luce"],
                ["Acqua", "La luce devia quando entra nel bicchiere"],
                ["Mente", "Il cervello cambia forma se impariamo"],
                ["Placche", "I continenti galleggiano sul fuoco fuso"],
                ["Cibo", "Il metabolismo trasforma il pane in forza"],
                ["Cerchio", "I pianeti girano su orbite ellittiche"],
                ["Aria", "L'atmosfera preme su di noi come un peso"],
                ["Insieme", "Il microbioma ci aiuta a stare bene"],
                ["Corrente", "Gli elettroni corrono dentro il rame"],
                ["Inizio", "L'universo nacque con una grande esplosione"],
                ["Robot", "Le sonde esplorano i pianeti per noi"]
            ],
            spettacolo: [
                ["Sipario", "Il velluto si apre per mostrare la scena"],
                ["Parete", "Gli attori non vedono chi sta guardando"],
                ["Trucchi", "Gli effetti rendono vero ciò che è finto"],
                ["Statuetta", "L'Oscar premia i migliori film dell'anno"],
                ["Musical", "A Broadway si balla e si canta sul palco"],
                ["Circo", "Il clown fa ridere con gesti molto buffi"],
                ["Rischio", "Lo stuntman fa le scene più pericolose"],
                ["Cinema", "A Cinecittà sono nati capolavori famosi"],
                ["Maschera", "Anticamente serviva per farsi sentire"],
                ["Tappeto", "Le star sfilano sul tappeto rosso acceso"],
                ["Copione", "Contiene ogni parola detta dagli attori"],
                ["Voci", "I doppiatori parlano al posto delle star"],
                ["Ombre", "Le mani creano storie contro un telo"],
                ["Mimo", "Racconta tutto senza dire una parola"],
                ["Realtà", "I reality mostrano la vita delle persone"],
                ["Prima", "La proiezione che inaugura un nuovo film"],
                ["Pupazzo", "Il ventriloquo parla con la pancia chiusa"],
                ["Quinte", "Dietro lo show succede di tutto e di più"],
                ["Abiti", "Il costumista crea vestiti di ogni epoca"],
                ["Scelta", "Il casting serve a trovare il volto giusto"],
                ["Pensieri", "Il monologo è un discorso fatto da soli"],
                ["Fili", "Le marionette si muovono grazie a fili"],
                ["Palco", "Il comico parla da solo davanti a tutti"],
                ["Diretta", "Lo show avviene mentre lo vedi in TV"],
                ["Set", "Il regista sceglie posti reali per i film"],
                ["Cameo", "Una persona famosa appare per pochi secondi"],
                ["Serie", "La sitcom fa ridere tra le mura di casa"],
                ["Posa", "Il teatro di posa è un grande studio vuoto"],
                ["Mago", "L'illusionista fa sparire le cose con arte"],
                ["Broadway", "La strada di New York famosa per gli show"],
                ["Trama", "L'intreccio tiene tutti incollati al video"],
                ["Spalla", "L'attore che aiuta a far ridere il pubblico"],
                ["Luci", "I fuochi d'artificio chiudono la festa"],
                ["Gesti", "La pantomima è una danza fatta di mosse"],
                ["Passi", "Il coreografo inventa i balli del gruppo"],
                ["Finale", "Lo spoiler rovina la sorpresa a chi guarda"],
                ["Tensione", "Il climax è il punto più alto della storia"],
                ["Telo", "Il green screen serve per gli sfondi PC"],
                ["Spot", "I video che servono per vendere i prodotti"],
                ["Trucco", "Nel camerino gli attori cambiano faccia"],
                ["Risate", "La parodia prende in giro le opere serie"],
                ["Testi", "Il drammaturgo scrive opere per il teatro"],
                ["Fisse", "Arlecchino è un tipo della commedia arte"],
                ["Prove", "Il teatro d'avanguardia sperimenta tutto"],
                ["Musa", "L'ispirazione che muove la mano dell'artista"],
                ["Mani", "L'applauso premia chi ha recitato bene"],
                ["Cannes", "Un festival di cinema molto elegante"],
                ["Musica", "La sigla introduce il mondo della serie"],
                ["Luce", "Il proiettore manda le immagini sullo schermo"],
                ["Capo", "Il regista decide ogni cosa sul set dei film"]
            ],
            storia: [
                ["Roma", "Le leggi romane univano tutto il mondo"],
                ["Parigi", "Il popolo chiese libertà ed uguaglianza"],
                ["America", "Colombo cercava le Indie e trovò terre"],
                ["Arte", "Il rinascimento nacque nelle città italiane"],
                ["Pietra", "Hammurabi scrisse le prime leggi su roccia"],
                ["Guerra", "Francia ed Inghilterra lottarono per anni"],
                ["Berlino", "Un muro divise la città per lungo tempo"],
                ["Egitto", "Le piramidi erano tombe per i grandi re"],
                ["Peste", "Il morbo nero uccise milioni di persone"],
                ["Libertà", "La Magna Carta diede diritti ai nobili"],
                ["Sbarco", "La Normandia fu l'inizio della libertà"],
                ["Stampa", "Gutenberg permise di leggere molti libri"],
                ["Grecia", "La democrazia è nata tra le mura di Atene"],
                ["Nord", "La guerra civile americana finì la schiavitù"],
                ["Selce", "Gli umani usavano sassi come strumenti"],
                ["Seta", "La via della seta collegava Roma alla Cina"],
                ["Templari", "Monaci guerrieri che proteggevano i viaggi"],
                ["Sfarzo", "Il barocco usava oro e grandi decorazioni"],
                ["Fredda", "Stati Uniti e Russia si sfidarono in pace"],
                ["Prigione", "La Bastiglia fu assalita dal popolo"],
                ["Navi", "I vichinghi arrivarono in America per primi"],
                ["Feudo", "Il signore dava terra in cambio di difesa"],
                ["Codice", "Napoleone scrisse le leggi moderne"],
                ["Mongoli", "Gengis Khan conquistò mezza terra"],
                ["Trincea", "La prima guerra mondiale fu nel fango"],
                ["Voto", "Le donne lottarono per poter votare"],
                ["Nelson", "Mandela vinse la lotta contro il razzismo"],
                ["Fiumi", "La civiltà nacque tra Tigri ed Eufrate"],
                ["Vapore", "Le macchine cambiarono il modo di lavorare"],
                ["Oriente", "Costantinopoli cadde sotto i turchi"],
                ["Bushido", "I samurai seguivano un codice d'onore"],
                ["Riforma", "Lutero divise la chiesa con le sue idee"],
                ["Ragione", "L'illuminismo voleva portare luce nel buio"],
                ["Maya", "Piramidi giganti sorsero nella giungla"],
                ["Giungla", "Il Vietnam fu una guerra difficile e dura"],
                ["Pace", "I trattati di Westfalia crearono gli stati"],
                ["Cartagine", "Annibale sfidò Roma con gli elefanti"],
                ["Borsa", "Il crollo del ventinove mise tutti in crisi"],
                ["Macedonia", "Alessandro portò i greci fino all'India"],
                ["Nazioni", "L'Onu è nata per fermare nuove guerre"],
                ["Giza", "Le piramidi sono l'unica meraviglia rimasta"],
                ["Trento", "La chiesa si riunì per rispondere a Lutero"],
                ["Bisanzio", "L'impero d'oriente visse per mille anni"],
                ["Rose", "York e Lancaster lottarono per la corona"],
                ["Memoria", "La Shoah è il punto più buio della storia"],
                ["Spazio", "Il primo satellite fu lanciato dai russi"],
                ["Cina", "I Ming fecero la grande muraglia e vasi"],
                ["Spagna", "L'inquisizione dava la caccia agli eretici"],
                ["Ottimismo", "La Belle Epoque finì con la grande guerra"],
                ["Zar", "La rivoluzione russa cambiò tutto il mondo"]
            ]
        };